[tool.black]
line-length = 88
target-version = ["py311"]
include = '\\.pyi?$'
extend-exclude = '''
/(
  \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | build
  | dist
  | node_modules
  | __pycache__
  | .*\.ipynb_checkpoints
)/
'''
[tool.isort]
profile = "black"
line_length = 88
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
src_paths = ["src", "scripts", "examples", "tests", "streamlit_ui"]
known_first_party = ["src"]
known_third_party = ["pandas", "numpy", "sqlalchemy", "loguru", "click", "yfinance"]
skip = ["node_modules", "build", "dist"]

 
 
