# Trading Strategies Configuration
strategies:
  - name: "momentum_strategy"
    enabled: true
    description: "Simple momentum-based trading strategy"
    parameters:
      lookback_period: 20
      momentum_threshold: 0.02
      max_position_size: 0.1
      stop_loss: 0.05
      take_profit: 0.10
    risk_limits:
      max_drawdown: 0.05
      max_daily_loss: 0.02
      max_positions: 10
      max_sector_exposure: 0.3
    schedule:
      run_frequency: "hourly"
      market_hours_only: true

  - name: "mean_reversion_strategy"
    enabled: false
    description: "Mean reversion strategy for oversold/overbought conditions"
    parameters:
      lookback_period: 14
      rsi_oversold: 30
      rsi_overbought: 70
      position_size: 0.05
    risk_limits:
      max_drawdown: 0.03
      max_daily_loss: 0.015
      max_positions: 5
    schedule:
      run_frequency: "hourly"
      market_hours_only: true

  - name: "pairs_trading_strategy"
    enabled: true
    description: "Statistical arbitrage using correlated stock pairs"
    parameters:
      lookback_period: 252  # 1 year of daily data
      entry_threshold: 2.0  # Z-score threshold for entry
      exit_threshold: 0.5   # Z-score threshold for exit
      stop_loss_threshold: 3.0  # Z-score stop loss
      position_size: 0.05   # 5% of portfolio per pair
      rebalance_frequency: "daily"
    risk_limits:
      max_drawdown: 0.08
      max_daily_loss: 0.03
      max_positions: 8
      max_sector_exposure: 0.4
    schedule:
      run_frequency: "hourly"
      market_hours_only: true

# Global Strategy Settings
global_settings:
  paper_trading: true
  max_total_exposure: 0.8
  rebalance_frequency: "daily"
  log_level: "INFO"
